# A development environment for mingpt
name: mingpt

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - tqdm
  - numpy
  - pytorch
  - torchvision
  - jupyter
  - matplotlib
  - pip:
    - "-e ."
